name: 'Conditional status'
author: 'Leandro Lourenci'
description: 'Add a successful status as soon as some other specified status turns into successful'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  context:
    description: 'Name of the context to be checked'
    required: true
  token:
    description: 'Your GITHUB_TOKEN'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
